# -*- coding: utf-8 -*-
"""TensorFlow Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oVyEukxrQGrJbFPh937h2wvMMOm8qyb3
"""

pip install tensorflow

import tensorflow as tf
print(tf.__version__)

pip install transformers

"""**Pipeline 1**"""

from transformers import pipeline

classifier = pipeline("sentiment-analysis")
res = classifier("I'm excited to test my first imported model")
print(res)

"""**Pipeline 2**"""

generator = pipeline("text-generation", model="distilgpt2")

res = generator(
    "Tracy said that",
    max_length=30,
    num_return_sequences=10,
)

print(res)

"""**Pipeline 3**"""

classifier = pipeline("zero-shot-classification")

res = classifier(
    "This is a course about Python list comprehension",
    candidate_labels=["education", "politics", "business"]
)

print(res)

"""**Tokenizers**"""

